#!/bin/bash

# Final Correct Cloudflare API Token Creation Guide

echo "🔑 Create New Cloudflare API Token (FINAL CORRECT NAMES)"
echo "======================================================="
echo ""
echo "Based on what you're seeing in the Cloudflare interface, here are the EXACT permissions:"
echo ""

echo "📋 Step-by-Step Instructions:"
echo ""
echo "1. Go to: https://dash.cloudflare.com/profile/api-tokens"
echo ""
echo "2. Click 'Create Token'"
echo ""
echo "3. Choose 'Custom token'"
echo ""
echo "4. Set these EXACT permissions (based on what you see):"
echo "   ✅ Account:"
echo "      - D1:Edit"
echo "      - Workers Scripts:Edit        ← This is what you see!"
echo "      - Account Settings:Read"
echo "   ✅ User:"
echo "      - User Details:Read"
echo "   ✅ Zone:"
echo "      - Zone:Read"
echo "      - Zone Settings:Edit"
echo ""
echo "5. Set Account resources:"
echo "   - Include: Specific account"
echo "   - Account: Ucancallmebiru@gmail.com's Account"
echo ""
echo "6. Set Zone resources:"
echo "   - Include: All zones"
echo ""
echo "7. Click 'Continue to summary'"
echo ""
echo "8. Name: 'UncleSense Deployment Token'"
echo ""
echo "9. Click 'Create Token'"
echo ""
echo "10. Copy the NEW token"
echo ""
echo "11. Update your .env.local file:"
echo "    sed -i '' 's/CLOUDFLARE_API_TOKEN=.*/CLOUDFLARE_API_TOKEN=YOUR_NEW_TOKEN/' .env.local"
echo ""
echo "12. Test the new token:"
echo "    ./test-token.sh"
echo ""
echo "13. Deploy UncleSense:"
echo "    ./deploy.sh"
echo ""

echo "💡 Key Permission:"
echo "   - 'Workers Scripts:Edit' (not 'Workers:Edit' or 'Cloudflare Workers:Edit')"
echo "   - This should give Wrangler the permissions it needs for deployment"
