#!/bin/bash

echo "🔍 HuggingFace Account Debugging"
echo "==============================="
echo ""
echo "Let's check your HuggingFace account status:"
echo ""
echo "1. 🌐 Go to: https://huggingface.co/settings/tokens"
echo "2. 🔍 Check the following:"
echo ""
echo "   ✅ Are you logged in?"
echo "   ✅ Is your email verified?"
echo "   ✅ Do you see any account warnings?"
echo "   ✅ Are there any existing tokens?"
echo "   ✅ Is your account in good standing?"
echo ""
echo "3. 🧪 Test your account with a simple request:"
echo "   - Go to: https://huggingface.co/api/whoami"
echo "   - This should show your account info if logged in"
echo ""
echo "4. 🔑 If you see existing tokens:"
echo "   - Delete any old 'UncleSense' tokens"
echo "   - Create a fresh one"
echo ""
echo "5. 📧 If you see account issues:"
echo "   - Check your email for verification"
echo "   - Contact HuggingFace support if needed"
echo ""
echo "6. 🔄 Common fixes:"
echo "   - Log out and log back in"
echo "   - Clear browser cache"
echo "   - Try incognito/private mode"
echo "   - Check if you're on the right account"
