#!/bin/bash

# Subdomain Registration Guide

echo "🌐 Cloudflare Workers Subdomain Registration"
echo "============================================="
echo ""
echo "📋 Step-by-Step Instructions:"
echo ""
echo "1. Open your browser and go to:"
echo "   https://dash.cloudflare.com/9425323808f6bcb2d41e9a3115a653ec/workers/onboarding"
echo ""
echo "2. You should see a page titled 'Workers & Pages'"
echo ""
echo "3. Look for 'Workers' section and click 'Get started' or 'Create a Worker'"
echo ""
echo "4. You'll be prompted to register a subdomain"
echo "   - Choose something like: unclesense-api"
echo "   - Your API will be at: https://unclesense-api.YOUR_SUBDOMAIN.workers.dev"
echo ""
echo "5. After registration, try deploying again:"
echo "   ./deploy-final.sh"
echo ""
echo "🔄 Alternative: Try deploying with a custom route"
echo "   If subdomain registration doesn't work, we can deploy to a custom domain"
echo ""
echo "💡 Troubleshooting:"
echo "   - Make sure you're logged into the correct Cloudflare account"
echo "   - Check if you have Workers enabled in your account"
echo "   - Try refreshing the page if it doesn't load"
echo ""
echo "🚀 Once subdomain is registered, your UncleSense API will be live!"
