#!/bin/bash

echo "🔑 HuggingFace API Key Setup"
echo "=========================="
echo ""
echo "The current HuggingFace API key is invalid. Let's get a new one!"
echo ""
echo "📋 Steps to get a new HuggingFace API key:"
echo ""
echo "1. Go to: https://huggingface.co/settings/tokens"
echo "2. Click 'New token'"
echo "3. Give it a name like 'UncleSense'"
echo "4. Select 'Read' permissions (that's all we need)"
echo "5. Click 'Generate a token'"
echo "6. Copy the token (it starts with 'hf_')"
echo ""
echo "⚠️  IMPORTANT: Copy the token immediately - you won't be able to see it again!"
echo ""
echo "Once you have the token, run:"
echo "  ./update-huggingface-key.sh"
echo ""
echo "Or manually update it in .env.local:"
echo "  VITE_HUGGINGFACE_API_KEY=your_new_token_here"
echo ""
echo "🔍 Current API key status: INVALID"
echo "   The current API key is not working."
echo ""
echo "💡 Tip: Make sure you're logged into HuggingFace with the same account"
echo "   that you want to use for UncleSense."
