#!/bin/bash

# Template Token Solution for Wrangler Deployment

echo "🔧 Template Token Solution"
echo "=========================="
echo ""
echo "The /memberships endpoint is failing with your custom token."
echo "This is a known issue with Wrangler and custom API tokens."
echo ""
echo "💡 Solution: Use a Cloudflare template token instead"
echo ""
echo "📋 Step-by-Step Instructions:"
echo ""
echo "1. Go to: https://dash.cloudflare.com/profile/api-tokens"
echo ""
echo "2. Click 'Create Token'"
echo ""
echo "3. Choose 'Use template'"
echo ""
echo "4. Select 'Edit zone DNS' template"
echo "   (This gives broader permissions that work with Wrangler)"
echo ""
echo "5. Click 'Continue to summary'"
echo ""
echo "6. Name: 'UncleSense-Template-Token'"
echo ""
echo "7. Click 'Create Token'"
echo ""
echo "8. Copy the NEW token"
echo ""
echo "9. Update your .env.local:"
echo "    sed -i '' 's/CLOUDFLARE_API_TOKEN=.*/CLOUDFLARE_API_TOKEN=YOUR_NEW_TOKEN/' .env.local"
echo ""
echo "10. Test and deploy:"
echo "    ./test-token.sh"
echo "    ./deploy.sh"
echo ""
echo "💡 Why this works:"
echo "   - Template tokens have pre-configured permissions"
echo "   - They include the /memberships endpoint access"
echo "   - Wrangler is designed to work with template tokens"
echo ""
echo "🔄 Alternative: Try OAuth login"
echo "   If template token doesn't work, we can try:"
echo "   npx wrangler login"
echo "   (This opens browser for OAuth authentication)"
