#!/bin/bash

# Template Token Creation Guide

echo "🔧 Template Token Creation Guide"
echo "=================================="
echo ""
echo "The current token is not working. Let's create a template token."
echo ""
echo "📋 Step-by-Step Instructions:"
echo ""
echo "1. Go to: https://dash.cloudflare.com/profile/api-tokens"
echo ""
echo "2. Click 'Create Token'"
echo ""
echo "3. Choose 'Use template' (NOT 'Custom token')"
echo ""
echo "4. Select 'Edit zone DNS' template"
echo "   - This gives the right permissions for Wrangler"
echo "   - Includes access to all necessary endpoints"
echo ""
echo "5. Click 'Continue to summary'"
echo ""
echo "6. Name: 'UncleSense-Template-Token'"
echo ""
echo "7. Click 'Create Token'"
echo ""
echo "8. Copy the NEW token"
echo ""
echo "9. Update your .env.local:"
echo "    sed -i '' 's/CLOUDFLARE_API_TOKEN=.*/CLOUDFLARE_API_TOKEN=YOUR_NEW_TOKEN/' .env.local"
echo ""
echo "10. Test the token:"
echo "    ./test-token.sh"
echo ""
echo "11. Deploy UncleSense:"
echo "    ./deploy.sh"
echo ""
echo "💡 Why template tokens work better:"
echo "   - Pre-configured permissions"
echo "   - Tested with Wrangler"
echo "   - Include all necessary endpoints"
echo "   - Avoid custom permission issues"
echo ""
echo "🔄 Alternative: Try OAuth login"
echo "   If template token doesn't work:"
echo "   npx wrangler login"
echo "   (This opens browser for OAuth authentication)"
